name: master

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '3 30 * * 7'

jobs:
  publish_image:
    name: Publish Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment variables
        run: |
          APP_VERSION=$(date '+%Y-%m-%d')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/386
          tags: cnbian/samba:${{ env.APP_VERSION }},cnbian/samba:latest